### ISSUE TITLE
[Validator] Add narrative-only validations for Bundle

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-validator-api#152]
**Is your feature request related to a problem? Please describe.**
The FHIR specification contains a set of content rules for Bundles, depending on the type of bundle. Quite a few of these are not expressed as FhirPath invariants (it is not always possible to do so), so they should be implemented in the validator by hand.

**Describe the solution you'd like**
We should add more validations stated in the description of bundles and documents.

**Additional context**
See the second part of this discussion on Zulip:  https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/Firely.20-.20Unable.20to.20resolve.20reference.20to.20profile where the Java validator returns `Bundle entry missing fullUrl or Except for transactions and batches, each entry in a Bundle must have a fullUrl which is the identity of the resource in the entry,` but we do return success.

**Comment by mmsmits** [comment]
Should be done in enterprise validator

**Comment by Kasdejong** [comment]
After some investigation, I found out that the R5 structure definition does actually cover all rules with FP invariants. Here's a quick summary:

| Rule          | description                                                                                                                                                            | expression                                                                                                                                               |
| ------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- |
| bdl-1         | total only when a search or history                                                                                                                                    | total.empty() or (type = 'searchset') or (type = 'history')                                                                                              |
| bdl-2         | entry.search only when a search                                                                                                                                        | (type = 'searchset') or entry.search.empty()                                                                                                             |
| bdl-3         | entry.request mandatory for batch/transaction/history, otherwise prohibited                                                                                            | entry.all(request.exists() = (%resource.type = 'batch' or %resource.type = 'transaction' or %resource.type = 'history'))                                 |
| bdl-3a        | For collections of type document, message, searchset or collection, all entries must contain resources, and not have request or response elements                      | type in ('document' \| 'message' \| 'searchset' \| 'collection') implies entry.all(resource.exists() and request.empty() and response.empty())           |
| bdl-3b        | For collections of type history, all entries must contain request or response elements, and resources if the method is POST, PUT or PATCH                              | type = 'history' implies entry.all(request.exists() and response.exists() and ((request.method in ('POST' \| 'PATCH' \| 'PUT')) = resource.exists()))    |
| bdl-3c        | For collections of type transaction or batch, all entries must contain request elements, and resources if the method is POST, PUT or PATCH                             | type in ('transaction' \| 'batch') implies entry.all(request.method.exists() and ((request.method in ('POST' \| 'PATCH' \| 'PUT')) = resource.exists())) |
| bdl-3d        | For collections of type transaction-response or batch-response, all entries must contain response elements                                                             | type in ('transaction-response' \| 'batch-response') implies entry.all(response.exists())                                                                |
| bdl-5 (entry) | must be a resource unless there's a request or response                                                                                                                | resource.exists() or request.exists() or response.exists()                                                                                               |
| bdl-7         | FullUrl must be unique in a bundle, or else entries with the same fullUrl must have different meta.versionId (except in history bundles)                               | (type = 'history') or entry.where(fullUrl.exists()).select(fullUrl&iif(resource.meta.versionId.exists(), resource.meta.versionId, '')).isDistinct()      |
| bdl-8 (entry) | fullUrl cannot be a version specific reference                                                                                                                         | fullUrl.exists() implies fullUrl.contains('/_history/').not()                                                                                            |
| bdl-9         | A document must have an identifier with a system and a value                                                                                                           | type = 'document' implies (identifier.system.exists() and identifier.value.exists())                                                                     |
| bdl-10        | A document must have a date                                                                                                                                            | type = 'document' implies (timestamp.hasValue())                                                                                                         |
| bdl-11        | A document must have a Composition as the first resource                                                                                                               | type = 'document' implies entry.first().resource.is(Composition)                                                                                         |
| bdl-12        | A message must have a MessageHeader as the first resource                                                                                                              | type = 'message' implies entry.first().resource.is(MessageHeader)                                                                                        |
| bdl-13        | A subscription-notification must have a SubscriptionStatus as the first resource                                                                                       | type = 'subscription-notification' implies entry.first().resource.is(SubscriptionStatus)                                                                 |
| bdl-14        | entry.request.method PATCH not allowed for history                                                                                                                     | type = 'history' implies entry.request.method != 'PATCH'                                                                                                 |
| bdl-15        | Bundle resources where type is not transaction, transaction-response, batch, or batch-response or when the request is a POST SHALL have Bundle.entry.fullUrl populated | type='transaction' or type='transaction-response' or type='batch' or type='batch-response' or entry.all(fullUrl.exists() or request.method='POST')       |
| bdl-16        | Issue.severity for all issues within the OperationOutcome must be either 'information' or 'warning'.                                                                   | issues.exists() implies (issues.issue.severity = 'information' or issues.issue.severity = 'warning')                                                     |
| bdl-17        | Use and meaning of issues for documents has not been validated because the content will not be rendered in the document.                                               | type = 'document' implies issues.empty()                                                                                                                 |
| bdl-18        | Self link is required for searchsets.                                                                                                                                  | type = 'searchset' implies link.where(relation = 'self' and url.exists()).exists()                                                                       |


| Rule          | r5       |                 | r4       |                 | r3       |                 |
| ------------- | -------- | --------------- | -------- | --------------- | -------- | --------------- |
|               | Has rule | Defined in text | Has rule | Defined in text | Has rule | Defined in text |
| bdl-1         | x        | x               | x        | x               | x        | x               |
| bdl-2         | x        | x               | x        | x               | x        | x               |
| bdl-3         |          |                 | x        | x               | x        | x               |
| bdl-3a        | x        | x               |          | x               |          | x               |
| bdl-3b        | x        | x               |          | x               |          | x               |
| bdl-3c        | x        | x               |          | x               |          | x               |
| bdl-3d        | x        | x               |          | x               |          | x               |
| bdl-5 (entry) | x        | x               | x        | x               | x        | x               |
| bdl-7         | x        | x               | x        | x               | x        | x               |
| bdl-8 (entry) | x        | x               | x        | x               | x        | x               |
| bdl-9         | x        | x               | x        | x               | x        | x               |
| bdl-10        | x        | x               | x        | x               |          | x               |
| bdl-11        | x        | x               | x        | x               |          | x               |
| bdl-12        | x        | x               | x        | x               |          | x               |
| bdl-13        | x        | x               |          |                 |          |                 |
| bdl-14        | x        | x               |          |                 |          |                 |
| bdl-15        | x        | x               |          | x               |          | x               |
| bdl-16        | x        | x               |          |                 |          |                 |
| bdl-17        | x        | x               |          |                 |          |                 |
| bdl-18        | x        | x               |          |                 |

**Comment by Kasdejong** [comment]
I suggest we correct the structure definitions at resolve time rather than hand writing the rules for these, as they are well defined in R5.
